# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Basic Information
title: My DASHBox
description: An open-source toolkit for reproducible and well-documented data analysis projects.
show_downloads: false

# Images
logo: assets/img/dash.png
